### ISSUE TITLE
How to train the SegAN?

### ISSUE THREAD

**Issue by NeuZhangQiang** [gokriznastic/SegAN#1]
Thank you very much for sharing SegAN. Currently, I apply the SegAN to segment the rib. If I use the Unet with the resnet as the backbone, the dice can achieve 0.85. But for SegAN, I can only obtain dice of 0.7. Do you have any suggestion?

**Comment by blublebee** [comment]
Traceback (most recent call last):
  File "D:\PycharmFile\ImageSegmentation\GAN\SegAN-master\train.py", line 123, in <module>
    for i, data in tqdm(enumerate(dataloader, 1)):
  File "E:\anaconda\envs\pytorch\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\PycharmFile\ImageSegmentation\GAN\SegAN-master\data_loader.py", line 83, in __getitem__
    image = imread(self.imagePath)
  File "E:\anaconda\envs\pytorch\lib\site-packages\tifffile\tifffile.py", line 715, in imread
    with TiffFile(files, **kwargs_file) as tif:
  File "E:\anaconda\envs\pytorch\lib\site-packages\tifffile\tifffile.py", line 2228, in __init__
    fh = FileHandle(arg, mode='rb', name=name, offset=offset, size=size)
  File "E:\anaconda\envs\pytorch\lib\site-packages\tifffile\tifffile.py", line 6031, in __init__
    self.open()
  File "E:\anaconda\envs\pytorch\lib\site-packages\tifffile\tifffile.py", line 6044, in open
    self._fh = open(self._file, self._mode)
PermissionError: [Errno 13] Permission denied: 'D:\\PycharmFile\\ImageSegmentation\\GAN\\SegAN-master\\preprocessed\\train\\sampleimages\\volume'



Why does this error still occur when I use the lits dataset

**Comment by blublebee** [comment]
> Thank you very much for sharing SegAN. Currently, I apply the SegAN to segment the rib. If I use the Unet with the resnet as the backbone, the dice can achieve 0.85. But for SegAN, I can only obtain dice of 0.7. Do you have any suggestion?
could you share your code for me？I can‘t run this code，the code can’t open .nii file.
